# Generated by Django 4.0.6 on 2022-07-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_unique_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_name_no_parent_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_name_parent_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_order_no_parent_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_order_parent_uniq",
        ),
        migrations.AlterField(
            model_name="category",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("project", "name"),
                name="core_category_name_no_parent_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "name"),
                name="core_category_name_parent_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("project", "order"),
                name="core_category_order_no_parent_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "order"),
                name="core_category_order_parent_uniq",
            ),
        ),
    ]
