# Generated by Django 4.1b1 on 2022-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_use_mptt_for_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="quantity_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="interval_quantity",
            field=models.IntegerField(
                blank=True,
                help_text="The quantity that will be reset at the beginning of each day, week or month (must not be set in reverse mode)",
                null=True,
                verbose_name="quantity",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="reverse_mode",
            field=models.BooleanField(
                default=False,
                help_text="If set, the quantity will be computed automatically",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("interval_quantity__isnull", False),
                    ("reverse_mode", True),
                    _connector="OR",
                ),
                name="core_project_interval_quantity_null_in_reverse_mode",
                violation_error_message="Quantity must not be set in reverse mode",
            ),
        ),
    ]
