# Generated by Django 4.1b1 on 2022-07-07 22:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_fix_project_quantity_constraint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quantity",
            old_name="start_date",
            new_name="interval_start_date",
        ),
        migrations.RemoveField(
            model_name="quantity",
            name="end_date",
        ),
        migrations.AddField(
            model_name="quantity",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quantity",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="category",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quantities",
                to="core.category",
            ),
        ),
    ]
