# Generated by Django 4.1b1 on 2022-07-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_change_quantity_dates"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="quantity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("start_at__isnull", True),
                    ("end_at__isnull", True),
                    ("start_at__lt", models.F("end_at")),
                    _connector="OR",
                ),
                name="core_quantity_start_at_lower_than_end_at",
                violation_error_message="The start date must be lower than the end date.",
            ),
        ),
    ]
