# Generated by Django 4.1b1 on 2022-07-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_quantity_index_category_interval_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantity",
            name="interval_start_date",
            field=models.DateField(null=True),
        ),
    ]
