# Generated by Django 4.1b1 on 2022-07-08 11:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_category_order_to_sort_order_step2"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("_tree_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("project", "parent", "sort_order")},
        ),
    ]
