# Generated by Django 4.1b1 on 2022-07-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_use_orderable_for_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="expected_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
