# Generated by Django 4.1b1 on 2022-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_category_expected_quantity"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[],
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="core_project_interval_quantity_null_in_reverse_mode",
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("reverse_mode", True), ("interval_quantity__isnull", True)),
                    ("reverse_mode", False),
                    _connector="OR",
                ),
                name="core_project_interval_quantity_null_in_reverse_mode",
                violation_error_message="Quantity cannot be set in reverse mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("reverse_mode", False), ("interval_quantity__isnull", False)),
                    ("reverse_mode", True),
                    _connector="OR",
                ),
                name="core_project_interval_quantity_not_null_in_no_reverse_mode",
                violation_error_message="Quantity must be set if not in reverse mode",
            ),
        ),
    ]
