# Generated by Django 4.1b1 on 2022-07-09 12:18

import core.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_project_quantity_reverse_mode_double_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=core.fields.TreeForeignKeyNoRoot(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="category",
            field=core.fields.TreeForeignKeyNoRoot(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quantities",
                to="core.category",
            ),
        ),
    ]
