# Generated by Django 4.1b1 on 2022-07-09 12:18

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_category_use_field_hiding_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="quick_add_quantities",
            field=models.TextField(
                blank=True,
                help_text="A list of quantities available as quick add buttons. Each quantity is separated by a comma. Example: 1,2,5,10,20,50,100",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
    ]
