# Generated by Django 4.1b1 on 2022-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_project_quick_add_quantities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("monthly", "monthly"),
                    ("yearly", "yearly"),
                    ("none", "none"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="interval_quantity",
            field=models.IntegerField(
                blank=True,
                help_text="The quantity that will be reset at the beginning of each day, week, month or year (must not be set in reverse mode)",
                null=True,
                verbose_name="quantity",
            ),
        ),
    ]
