# Generated by Django 4.1b1 on 2022-07-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_project_yearly_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantity",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Start date"),
        ),
    ]
