# Generated by Django 4.1b1 on 2022-07-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_start_at_end_at_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="expected_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
