# Generated by Django 4.1b1 on 2022-07-31 12:51

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_category_expected_quantity_positive"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_order_no_parent_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="core_category_order_parent_uniq",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("parent", "sort_order"),
                name="core_category_order_parent_uniq",
                violation_error_message="A category with this order already exists in this category.",
            ),
        ),
    ]
