# Generated by Django 4.1b1 on 2022-07-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_category_sort_order_constraint_deferrable"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
    ]
