# Generated by Django 4.1b1 on 2022-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_category_remove_unique_together"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("project",),
                name="core_category_no_parent_uniq",
                violation_error_message="A project can only have one root category",
            ),
        ),
    ]
