# Generated by Django 4.1b1 on 2022-08-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_only_one_root_category_per_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("monthly", "monthly"),
                    ("yearly", "yearly"),
                    ("none", "none"),
                    ("alltime", "alltime"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
