# Generated by Django 4.1b1 on 2022-08-07 02:39

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_project_sortable_step2_set_default_orders"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("owner", "sort_order"),
                name="core_project_order_owner_uniq",
                violation_error_message="A project with this order already exists.",
            ),
        ),
    ]
