# Generated by Django 4.1b1 on 2022-08-08 02:11
from datetime import datetime

from django.db import migrations
from django.db.models import F


def copy_start_at_to_interval_start_date(apps, schema_editor):
    Quantity = apps.get_model("core", "Quantity")
    Quantity.objects.filter(start_at__isnull=False).update(
        interval_start_date=F("start_at")
    )
    Quantity.objects.filter(interval_start_date__isnull=True).update(
        interval_start_date=datetime.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_project_sortable_step3_add_constraint"),
    ]

    operations = [
        migrations.RunPython(
            copy_start_at_to_interval_start_date,
            migrations.RunPython.noop,
        )
    ]
