# Generated by Django 4.1b1 on 2022-08-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_quantity_better_date_step1_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quantity",
            options={"ordering": ["-interval_start_date"], "verbose_name_plural": "quantities"},
        ),
        migrations.RemoveConstraint(
            model_name="quantity",
            name="core_quantity_start_at_lower_than_end_at",
        ),
        migrations.RemoveField(
            model_name="quantity",
            name="end_at",
        ),
        migrations.RemoveField(
            model_name="quantity",
            name="start_at",
        ),
    ]
