# Generated by Django 4.1b1 on 2022-08-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_quantity_better_date_step2_remove_start_end_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quantity",
            options={"ordering": ["-datetime"], "verbose_name_plural": "quantities"},
        ),
        migrations.RemoveIndex(
            model_name="quantity",
            name="core_quanti_categor_150206_idx",
        ),
        migrations.RenameField(
            model_name="quantity",
            old_name="interval_start_date",
            new_name="datetime",
        ),
        migrations.AddIndex(
            model_name="quantity",
            index=models.Index(fields=["category", "datetime"], name="core_quanti_categor_52f76d_idx"),
        ),
    ]
