# Generated by Django 4.1b1 on 2022-08-08 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_quantity_better_date_step3_rename_interval_start_date_to_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantity",
            name="datetime",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
