# Generated by Django 4.1b1 on 2022-08-08 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_quantity_better_date_step4_datetime_mandatory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantity",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
