# Generated by Django 4.1 on 2022-08-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_quantity_better_date_step5_datetime"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="core_project_interval_quantity_null_in_reverse_mode",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="core_project_interval_quantity_not_null_in_no_reverse_mode",
        ),
        migrations.RemoveField(
            model_name="project",
            name="reverse_mode",
        ),
        migrations.AlterField(
            model_name="project",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("monthly", "monthly"),
                    ("yearly", "yearly"),
                    ("none", "none"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="interval_quantity",
            field=models.IntegerField(
                blank=True,
                help_text="The quantity that will be reset at the beginning of each day, week, month or year (or never if no interval)",
                null=True,
                verbose_name="Limit quantity",
            ),
        ),
    ]
