# Generated by Django 4.1 on 2022-08-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_project_remove_reverse_mode_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="quantity_name",
            field=models.CharField(
                help_text="The name of the thing to count: euros, minutes, kilometers, etc.", max_length=100
            ),
        ),
    ]
