# Generated by Django 4.1 on 2022-09-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_project_goal_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
    ]
