# Generated by Django 4.1 on 2022-09-04 06:40

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_quantity_remove_name_rename_description_to_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="goal_mode",
            field=models.BooleanField(
                default=False,
                help_text="If a limit is set, you should not exceed it, but it can also be a goal you should reach.",
                verbose_name="Is this limit a goal?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("none", "No timeframe"),
                ],
                default="none",
                help_text="Example of usage: monthly expenses, daily minutes of sport,...",
                max_length=10,
                verbose_name="What is the timeframe?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="interval_quantity",
            field=models.IntegerField(
                blank=True,
                help_text="Example of usage: 1500€ per month, 30 minutes per day, 10km per week,...",
                null=True,
                verbose_name="What is the optional limit per timeframe?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, verbose_name="What is the name of this project?"),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_name",
            field=models.CharField(
                help_text="Dollars, €, minutes, 👟, kilometers, 📞 to mom,...",
                max_length=100,
                verbose_name="What do you want to count?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quick_add_quantities",
            field=models.TextField(
                blank=True,
                help_text="Optional. Each amount is separated by a comma. Example: 1,2,5,10,20,50,100",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^(\\s*\\d+\\s*,)*\\s*\\d+\\s*$"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
                verbose_name="What are the most common amounts you expect to enter?",
            ),
        ),
    ]
