# Generated by Django 4.1 on 2022-09-05 00:39

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_quantity_split_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="expected_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If set, should include the planned amounts of sub-categories.",
                null=True,
                verbose_name="What is the (optional) planned amount?",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="What is the name of this category?"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=core.fields.TreeForeignKeyNoRoot(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.category",
                verbose_name="What is the (optional) parent category?",
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="category",
            field=core.fields.TreeForeignKeyNoRoot(
                help_text="If you want to save a quantity in a sub-category, you need to create it first.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quantities",
                to="core.category",
                verbose_name="In which category to save this quantity?",
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="You can save a quantity for a past, present, or future date.",
                verbose_name="For which date do you want to save this quantity?",
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="You can add some notes about this quantity. They will be displayed in the list of quantities.",
                verbose_name="Optional notes",
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="time",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="This is totally optional.",
                null=True,
                verbose_name="Do you need to set a specific time?",
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="value",
            field=models.PositiveIntegerField(
                help_text="In %(quantity_name)s", verbose_name="What is the amount to save?"
            ),
        ),
    ]
